"""add plan to user

Revision ID: b45f5ff46297
Revises: fe58c88e36a3
Create Date: 2026-05-09 02:31:40.570945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45f5ff46297'
down_revision = 'fe58c88e36a3'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True, server_default='free'))

    op.execute("UPDATE \"user\" SET plan = 'free' WHERE plan IS NULL;")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('plan', existing_type=sa.String(length=20), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plan')

